version: '3.8'

services:
  gitlab-webhook-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gitlab-webhook-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # 端口配置
      - PORT=3000

      # Mastra API 服务地址
      # 注意：如果 Mastra API 也在同一个 Docker 网络中，使用容器名称
      # 如果在不同服务器，使用实际 URL
      - MASTRA_API_URL=${MASTRA_API_URL:-http://localhost:4111}

      # GitLab 配置
      - GITLAB_URL=${GITLAB_URL:-https://gitlab.com}
      - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
      - GITLAB_PROJECT_ID=${GITLAB_PROJECT_ID}
      - GITLAB_WEBHOOK_SECRET=${GITLAB_WEBHOOK_SECRET}

      # 钉钉配置
      - DINGTALK_WEBHOOK_URL=${DINGTALK_WEBHOOK_URL}
      - DINGTALK_SECRET=${DINGTALK_SECRET}

    # 健康检查
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); });"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M

    # 网络配置
    networks:
      - gitlab-review-network

networks:
  gitlab-review-network:
    driver: bridge
